Added Key Status to project.java
Need to delete all the unnecessary columns in the project table because of the following error. The table is full because of the older version of scorecard.

ERROR: HHH000388: Unsuccessful: alter table Project add column keyStatus varchar(300)
Jun 25, 2020 11:17:34 AM org.hibernate.tool.hbm2ddl.SchemaUpdate execute
ERROR: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs